name: Create Docker images

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Login to QALIPSIS private registry
        uses: docker/login-action@v2
        with:
          registry: qfagebzx.gra7.container-registry.ovh.net
          username: ${{ secrets.PROPRIETARY_DOCKER_USERNAME }}
          password: ${{ secrets.PROPRIETARY_DOCKER_PASSWORD }}

      - name: Build and publish the Docker running images for the head, factory and standalone
        run: ./gradlew build :head:dockerPush :factory:dockerPush :standalone:dockerPush

      - name: Prepare the files for the Docker factory builder images
        run: ./gradlew :factory-builder:dockerPrepare :factory-builder-with-plugins:dockerPrepare

      - name: Build and publish the Docker factory builder images without plugins
        run: |
          chmod +x ./factory-builder/build/docker/create-factory-builder-image.sh
          ./factory-builder/build/docker/create-factory-builder-image.sh

      - name: Build and publish the Docker factory builder images with plugins
        run: |
          chmod +x ./factory-builder-with-plugins/build/docker/create-factory-builder-image.sh
          ./factory-builder-with-plugins/build/docker/create-factory-builder-image.sh